### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ggmartins** [cdalvaro/docker-salt-master#171]
I had to downgrade docker-compose file to 3.3. Like the file below. I'm getting connection refused for the ports and /var/log/salt/master is logging the messages below, tell me if this looks like a bug, I can report it as so (using the template). I've also noticed that, there's no configuration in /home/salt/data/config/. I've added a master.conf with default ports but no luck. Thanks for any help.
```
version: '3.3'
volumes:
  roots:
  keys:
  logs:
services:
  master:
    container_name: salt_master_engage1
    image: ghcr.io/cdalvaro/docker-salt-master:latest
    restart: always
    volumes:
      - "roots/:/home/salt/data/srv"
      - "keys/:/home/salt/data/keys"
      - "logs/:/home/salt/data/logs"
    ports:
      - "4505:4505"
      - "4506:4506"
      ### salt-api port
      # - "8000:8000"
    healthcheck:
      test: ["CMD", "/usr/local/sbin/healthcheck"]
      #start_period: 30s
    environment:
      DEBUG: 'false'
      TZ: America/Chicago
      PUID: 1000
      PGID: 1000
      SALT_LOG_LEVEL: info
      ### salt-api settings
      # SALT_API_SERVICE_ENABLED: 'True'
      # SALT_API_USER: salt_api
      # SALT_API_USER_PASS: 4wesome-Pass0rd
```

```
2022-10-31 10:12:57,968 [salt.modules.network:2143][ERROR   ][12952] Exception while creating a ThreadPoolExecutor for resolving FQDNs: can't start new thread
2022-10-31 10:12:57,986 [salt.modules.network:2143][ERROR   ][12951] Exception while creating a ThreadPoolExecutor for resolving FQDNs: can't start new thread
2022-10-31 10:12:57,995 [salt.modules.network:2143][ERROR   ][12950] Exception while creating a ThreadPoolExecutor for resolving FQDNs: can't start new thread
2022-10-31 10:12:57,996 [salt.modules.network:2143][ERROR   ][12949] Exception while creating a ThreadPoolExecutor for resolving FQDNs: can't start new thread
2022-10-31 10:12:58,007 [salt.modules.network:2143][ERROR   ][12948] Exception while creating a ThreadPoolExecutor for resolving FQDNs: can't start new thread
2022-10-31 10:12:58,066 [salt.utils.process:998 ][ERROR   ][13192] An un-handled exception from the multiprocessing process 'FileserverUpdate' was caught:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/salt/utils/process.py", line 993, in wrapped_run_func
    return run_func()
  File "/usr/local/lib/python3.10/dist-packages/salt/master.py", line 508, in run
    self.update_threads[interval].start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

**Comment by cdalvaro** [comment]
Hi!

Thank you very much for opening the issue!

The [`master.yml`](assets/runtime/config/master.yml) is automatically generated when the container starts.

If you need to add some specific configuration that you can't using env variables, create a .conf file that fulfill your needs. (You can see the [test](test) directory for some help)

I'll try to reproduce your bug and see if I can figure out a solution.

**Comment by cdalvaro** [comment]
Hi @ggmartins,

I've tried you compose file with the following tweaks and everything works fine:

```yml
version: '3.3'
volumes:
  roots:
  keys:
services:
  master:
    container_name: salt_master_engage1
    image: ghcr.io/cdalvaro/docker-salt-master:latest
    restart: always
    volumes:
      - "roots:/home/salt/data/srv/"
      - "keys:/home/salt/data/keys/"
      - "./logs/:/home/salt/data/logs/"
    ports:
      - "4505:4505"
      - "4506:4506"
      ### salt-api port
      # - "8000:8000"
    healthcheck:
      test: ["CMD", "/usr/local/sbin/healthcheck"]
      #start_period: 30s
    environment:
      DEBUG: 'false'
      TZ: America/Chicago
      PUID: 1000
      PGID: 1000
      SALT_LOG_LEVEL: info
      ### salt-api settings
      # SALT_API_SERVICE_ENABLED: 'True'
      # SALT_API_USER: salt_api
      # SALT_API_USER_PASS: 4wesome-Pass0rd
```

Please, could you test it??

**Comment by cdalvaro** [comment]
If you are viewing salt logs inside the `logs` volume, you should set the `[SALT_LEVEL_LOGFILE](https://docs.saltproject.io/en/latest/ref/configuration/master.html#log-level-logfile)` to `info` as well since, `SALT_LOG_LEVEL` is for the standard output.

I'll make some changes to use `SALT_LOG_LEVEL` when `SALT_LEVEL_LOGFILE` is not defined in order to make it less confusing.

**Comment by ggmartins** [comment]
ok, thanks, looks like your changes are working on one machine. The other server seems to be having problems connecting the minions, but we think the problem is with the server itself. Thank you so much for your help! Thanks for the tip on logging too.

**Comment by cdalvaro** [comment]
You are welcome!
