### ISSUE TITLE
Fileserver not work in gitfs mode

### ISSUE THREAD

**Issue by olegbukatchuk** [cdalvaro/docker-salt-master#261]
**Describe the bug**
```
saltstack  | [INFO    ] Wrote new gitfs remote map to /var/cache/salt/master/gitfs/remote_map.txt
saltstack  | [ERROR   ] Error occurred fetching gitfs remote 'git@git.example.com:saltstack/infr.git': remote rejected authentication: Failed getting response
saltstack  | Traceback (most recent call last):
saltstack  |   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 2025, in _fetch
saltstack  |     fetch_results = origin.fetch(**fetch_kwargs)
saltstack  |   File "/opt/saltstack/salt/extras-3.10/pygit2/remotes.py", line 160, in fetch
saltstack  |     payload.check_error(err)
saltstack  |   File "/opt/saltstack/salt/extras-3.10/pygit2/callbacks.py", line 99, in check_error
saltstack  |     check_error(error_code)
saltstack  |   File "/opt/saltstack/salt/extras-3.10/pygit2/errors.py", line 66, in check_error
saltstack  |     raise GitError(message)
saltstack  | _pygit2.GitError: remote rejected authentication: Failed getting response
```

**To Reproduce**
```
# config/fileserver.conf
gitfs_remotes:
  - git@git.example.com:saltstack/infr.git:
    - update_interval: 60
    - disable_saltenv_mapping: True
    - saltenv:
      - production:
        - ref: production
        - mountpoint: salt://production
      - dev:
        - ref: dev
        - mountpoint: salt://dev
```

**Expected behavior**
fileserver (gitfs) work!

**Additional info**
```
...
saltstack  | [INFO] - System initialized successfully!
saltstack  | Salt Version:
saltstack  |           Salt: 3007.1
saltstack  |
saltstack  | Python Version:
saltstack  |         Python: 3.10.14 (main, Apr  3 2024, 21:30:09) [GCC 11.2.0]
saltstack  |
saltstack  | Dependency Versions:
saltstack  |           cffi: 1.16.0
saltstack  |       cherrypy: 18.8.0
saltstack  |       dateutil: 2.8.2
saltstack  |      docker-py: Not Installed
saltstack  |          gitdb: Not Installed
saltstack  |      gitpython: Not Installed
saltstack  |         Jinja2: 3.1.4
saltstack  |        libgit2: 1.8.1
saltstack  |   looseversion: 1.3.0
saltstack  |       M2Crypto: Not Installed
saltstack  |           Mako: Not Installed
saltstack  |        msgpack: 1.0.7
saltstack  |   msgpack-pure: Not Installed
saltstack  |   mysql-python: Not Installed
saltstack  |      packaging: 23.1
saltstack  |      pycparser: 2.21
saltstack  |       pycrypto: Not Installed
saltstack  |   pycryptodome: 3.19.1
saltstack  |         pygit2: 1.15.1
saltstack  |   python-gnupg: 0.5.2
saltstack  |         PyYAML: 6.0.1
saltstack  |          PyZMQ: 25.1.2
saltstack  |         relenv: 0.16.0
saltstack  |          smmap: Not Installed
saltstack  |        timelib: 0.3.0
saltstack  |        Tornado: 6.3.3
saltstack  |            ZMQ: 4.3.4
saltstack  |
saltstack  | Salt Package Information:
saltstack  |   Package Type: onedir
saltstack  |
saltstack  | System Versions:
saltstack  |           dist: ubuntu 24.04 noble
saltstack  |         locale: utf-8
saltstack  |        machine: x86_64
saltstack  |        release: 5.15.0-119-generic
saltstack  |         system: Linux
saltstack  |        version: Ubuntu 24.04 noble
saltstack  |
saltstack  | [INFO] - Starting supervisord ...
saltstack  | 2024-09-27 09:35:06,878 INFO Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
saltstack  | 2024-09-27 09:35:06,878 INFO Included extra file "/etc/supervisor/conf.d/salt-api.conf" during parsing
saltstack  | 2024-09-27 09:35:06,878 INFO Included extra file "/etc/supervisor/conf.d/salt-master.conf" during parsing
saltstack  | 2024-09-27 09:35:06,878 INFO Included extra file "/etc/supervisor/conf.d/salt-minion.conf" during parsing
saltstack  | 2024-09-27 09:35:06,878 INFO Set uid to user 0 succeeded
saltstack  | 2024-09-27 09:35:06,883 INFO RPC interface 'supervisor' initialized
saltstack  | 2024-09-27 09:35:06,883 CRIT Server 'unix_http_server' running without any HTTP authentication checking
saltstack  | 2024-09-27 09:35:06,884 INFO supervisord started with pid 1
saltstack  | 2024-09-27 09:35:07,887 INFO spawned: 'salt-master' with pid 248
saltstack  | 2024-09-27 09:35:07,889 INFO spawned: 'salt-api' with pid 249
saltstack  | 2024-09-27 09:35:07,891 INFO spawned: 'cron' with pid 250
saltstack  | 2024-09-27 09:35:07,893 INFO spawned: 'salt-minion' with pid 252
saltstack  | [INFO    ] Setting up the Salt Master
saltstack  | [INFO    ] Preparing the salt key for local communication
saltstack  | 2024-09-27 09:35:09,036 INFO success: salt-master entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
saltstack  | 2024-09-27 09:35:09,037 INFO success: salt-api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
saltstack  | 2024-09-27 09:35:09,037 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
saltstack  | 2024-09-27 09:35:09,037 INFO success: salt-minion entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
saltstack  | [INFO    ] Preparing the root key for local communication
saltstack  | [INFO    ] Starting up the Salt Master
saltstack  | [WARNING ] Cache version mismatch clearing: '/var/cache/salt/master/gitfs'
saltstack  | [INFO    ] Wrote new gitfs remote map to /var/cache/salt/master/gitfs/remote_map.txt
saltstack  | [INFO    ] salt-master is starting as user 'salt'
saltstack  | [INFO    ] Current values for max open files soft/hard setting: 1048576/1048576
saltstack  | [INFO    ] Creating master process manager
saltstack  | [INFO    ] Creating master publisher process
saltstack  | [INFO    ] Creating master event publisher process
saltstack  | [INFO    ] Starting the Salt Publisher on tcp://0.0.0.0:4505
saltstack  | [INFO    ] Starting the Salt Puller on ipc:///var/run/salt/master/publish_pull.ipc
saltstack  | [INFO    ] Creating master maintenance process
saltstack  | [INFO    ] Creating master request server process
saltstack  | [INFO    ] Wrote new gitfs remote map to /var/cache/salt/master/gitfs/remote_map.txt
saltstack  | [INFO    ] Setting up the master communication server
saltstack  | [INFO    ] ReqServer clients tcp://0.0.0.0:4506
saltstack  | [INFO    ] ReqServer workers ipc:///var/run/salt/master/workers.ipc
saltstack  | [ERROR   ] Error occurred fetching gitfs remote 'git@git.example.com:saltstack/infr.git': remote rejected authentication: Failed getting response
saltstack  | Traceback (most recent call last):
saltstack  |   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 2025, in _fetch
saltstack  |     fetch_results = origin.fetch(**fetch_kwargs)
saltstack  |   File "/opt/saltstack/salt/extras-3.10/pygit2/remotes.py", line 160, in fetch
saltstack  |     payload.check_error(err)
saltstack  |   File "/opt/saltstack/salt/extras-3.10/pygit2/callbacks.py", line 99, in check_error
saltstack  |     check_error(error_code)
saltstack  |   File "/opt/saltstack/salt/extras-3.10/pygit2/errors.py", line 66, in check_error
saltstack  |     raise GitError(message)
saltstack  | _pygit2.GitError: remote rejected authentication: Failed getting response
```

**Version report (please complete the following information):**

- Host OS: `Linux salt.example.com 5.15.0-119-generic #129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
- Docker: `Docker version 27.2.1, build 9e34c9b`
- Image tag: `3007.1_2`

**Additional context**
If I try to clone the repository manually using the same key, everything works fine.
```
root@salt:~# ssh-add /opt/saltstack/ssh/gitfs_ssh
Identity added: /opt/saltstack/ssh/gitfs_ssh (gitfs_ed25519@salt.example.com
root@salt:~# git clone git@git.example.com:saltstack/infr.git
Cloning into 'infr'...
remote: Enumerating objects: 1209, done.
remote: Counting objects: 100% (151/151), done.
remote: Compressing objects: 100% (135/135), done.
remote: Total 1209 (delta 73), reused 6 (delta 6), pack-reused 1058 (from 1)
Receiving objects: 100% (1209/1209), 474.33 KiB | 11.57 MiB/s, done.
Resolving deltas: 100% (460/460), done.
```

**Comment by cdalvaro** [comment]
Hi @olegbukatchuk, thank you for opening this issue.

It looks like you have a typo in your settings:

```
[ERROR   ] Error occurred fetching gitfs remote '[git@git.exampla.com](mailto:git@git.exampla.com):saltstack/infr.git'
```

`git.exampla.com -> git.example.com`

Can you confirm that this is the real issue?

**Comment by olegbukatchuk** [comment]
> Hi @olegbukatchuk, thank you for opening this issue.
> 
> It looks like you have a typo in your settings:
> 
> ```
> [ERROR   ] Error occurred fetching gitfs remote '[git@git.exampla.com](mailto:git@git.exampla.com):saltstack/infr.git'
> ```
> 
> `git.exampla.com -> git.example.com`
> 
> Can you confirm that this is the real issue?

Yes, this is a real problem! I am changing the domain name because I don't want it to be mentioned anywhere.

**Comment by cdalvaro** [comment]
OK! Before anything, have you followed these steps: https://github.com/cdalvaro/docker-salt-master#git-fileserver ?

**Comment by olegbukatchuk** [comment]
> OK! Before anything, have you followed these steps: https://github.com/cdalvaro/docker-salt-master#git-fileserver ?
> 
> Specially those for specifying the path to your keys.

Yes, sure

**Comment by cdalvaro** [comment]
Could you provide your gitfs config file?

**Comment by olegbukatchuk** [comment]
> Could you provide your gitfs config file?

```
gitfs_provider: pygit2
gitfs_privkey: /home/salt/data/keys/gitfs/gitfs_ssh
gitfs_pubkey: /home/salt/data/keys/gitfs/gitfs_ssh.pub
```

in docker-compose.yml

```
volumes:
      - ./roots:/home/salt/data/srv
      - ./keys:/home/salt/data/keys
      - ./logs:/home/salt/data/logs
      - ./config:/home/salt/data/config
      - ./ssh/gitfs_ssh:/home/salt/data/keys/gitfs/gitfs_ssh:ro
      - ./ssh/gitfs_ssh.pub:/home/salt/data/keys/gitfs/gitfs_ssh.pub:ro
````

**Comment by cdalvaro** [comment]
Can you set the log level to `DEBUG`? Maybe we can find something useful there.

In your docker-compose.yml:

```yml
environment:
  - SALT_LOG_LEVEL=debug
```

**Comment by olegbukatchuk** [comment]
> Can you set the log level to `debug`? Maybe we can find something useful there.
> 
> In your docker-compose.yml:
> 
> ```yaml
> environment:
>   - SALT_LOG_LEVEL=debug
> ```
After enabling the DEBUG parameter, nothing changed in the logging of the repository image operation. I did not find any additional errors.
```
saltstack  | [ERROR   ] Error occurred fetching gitfs remote 'git@git.example.com:saltstack/infr.git': remote rejected authentication: Failed getting response
saltstack  | Traceback (most recent call last):
saltstack  |   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 2025, in _fetch
saltstack  |     fetch_results = origin.fetch(**fetch_kwargs)
saltstack  |   File "/opt/saltstack/salt/extras-3.10/pygit2/remotes.py", line 160, in fetch
saltstack  |     payload.check_error(err)
saltstack  |   File "/opt/saltstack/salt/extras-3.10/pygit2/callbacks.py", line 99, in check_error
saltstack  |     check_error(error_code)
saltstack  |   File "/opt/saltstack/salt/extras-3.10/pygit2/errors.py", line 66, in check_error
saltstack  |     raise GitError(message)
saltstack  | _pygit2.GitError: remote rejected authentication: Failed getting response
```

**Comment by cdalvaro** [comment]
With your salt-master container started (assuming your container's name is: `salt_master`), can you run the following commands?

```sh
docker run -it salt_master salt-run cache.clear_git_lock gitfs type=update
docker run -it salt_master salt-run -l debug fileserver.update
```

I'm trying to figure out what's happening, since [gitfs tests](https://github.com/cdalvaro/docker-salt-master/tree/main/tests/gitfs) are working.

**Comment by cdalvaro** [comment]
By the way @olegbukatchuk,

I've noticed that you've created a repository at https://github.com/olegbukatchuk/saltstack by directly copying this project without giving proper credit or acknowledging the LICENSE.

At the very least, it would have been appropriate to fork the original repository and then apply your changes.

**Comment by olegbukatchuk** [comment]
> By the way @olegbukatchuk,
> 
> I've noticed that you've created a repository at https://github.com/olegbukatchuk/saltstack by directly copying this project without giving proper credit or acknowledging the LICENSE.
> 
> At the very least, it would have been appropriate to fork the original repository and then apply your changes.

I deleted it so as not to disappoint you. It probably bothers you, sorry.

**Comment by cdalvaro** [comment]
I have no inconvenience if you want to keep your own copy. But if you are going to make it public, keep a reference to the original project.

**Comment by cdalvaro** [comment]
Related to this issue, did you try this: https://github.com/cdalvaro/docker-salt-master/issues/261#issuecomment-2378803453?

**Comment by cdalvaro** [comment]
OK, I'm sorry to hear that.

Feel free to reopen this issue if you want to try something, or if you find a solution.

You could try with a different git server using the same ssh key to discard whether is an issue with the key or the server.
