### ISSUE TITLE
SSL version error in pepper with 3001.1 image

### ISSUE THREAD

**Issue by vskubriev** [cdalvaro/docker-salt-master#38]
**Describe the bug**
I use 3001.1 image for up a master with api. When I done I try to connect via pepper(0.7.6) installed from pip. But faced with an error:

```
Error with request: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)>
<urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)>
Uncaught Pepper error (increase verbosity for the full traceback).
```
Also api.log has errors like this:

```
2020-10-02 15:23:45,895 [cherrypy.error   :219 ][INFO    ][181] [02/Oct/2020:15:23:45] ENGINE Listening for SIGTERM.
2020-10-02 15:23:45,896 [cherrypy.error   :219 ][INFO    ][181] [02/Oct/2020:15:23:45] ENGINE Listening for SIGHUP.
2020-10-02 15:23:45,896 [cherrypy.error   :219 ][INFO    ][181] [02/Oct/2020:15:23:45] ENGINE Listening for SIGUSR1.
2020-10-02 15:23:45,896 [cherrypy.error   :219 ][INFO    ][181] [02/Oct/2020:15:23:45] ENGINE Bus STARTING
2020-10-02 15:23:45,896 [cherrypy.error   :219 ][INFO    ][181] [02/Oct/2020:15:23:45] ENGINE Started monitor thread '_TimeoutMonitor'.
2020-10-02 15:23:46,003 [cherrypy.error   :219 ][INFO    ][181] [02/Oct/2020:15:23:46] ENGINE Serving on https://0.0.0.0:8000
2020-10-02 15:23:46,003 [cherrypy.error   :219 ][INFO    ][181] [02/Oct/2020:15:23:46] ENGINE Bus STARTED
2020-10-02 15:23:46,005 [cherrypy.error   :219 ][ERROR   ][181] [02/Oct/2020:15:23:46] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2021, in start
    self.tick()
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2090, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/ssl_builtin.py", line 66, in wrap
    s = self.context.wrap_socket(sock,do_handshake_on_connect=True,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
```
So I think we need to do something about it. Doesn't work out of the box or documentation needs clarification

That's is not critical for me at all.
I will try to figure out what's going on.

**Version report (please complete the following information):**
 - OS: [e.g. `5.4.0-47-generic`]
 - Docker: [`Docker version 19.03.13, build 4484c46d9d`]
 - Image tag: [e.g. 3001.1]

**Comment by vskubriev** [comment]
Removing outdated python package by `dpkg -r python3-cherrypy3`, and container restart allowed 

JFYI. To get rid of the error in api.log does:

```
dpkg -r python3-cherrypy3
pip3 install cherrypy
```
Restart container

Unfortunately this not solves pepper ssl error.

**Comment by cdalvaro** [comment]
Thank you so much for opening this issue.

I will work on it asap!

**Comment by vskubriev** [comment]
Tried to login with curl to api, but unfortunately:

`curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number`

I suspect ssl versions mismatch on server on client. Client is Ubuntu 20.04

May be that's something about TLS 1.3.

**Comment by cdalvaro** [comment]
At the moment I have tested this way on macOS Big Sur Beta 9:

```yml
# config/salt-api.conf
external_auth:
  pam:
    salt_api:
      - .*
      - '@runner'
      - '@wheel'
      - '@jobs'
```

```sh
docker run --name salt_master --detach \
  --publish 4505:4505 --publish 4506:4506 --publish 8000:8000 \
  --env 'SALT_API_SERVICE_ENABLED=true' \
  --env 'SALT_API_USER_PASS=4wesome-Pass0rd' \
  --env "USERMAP_UID=$(id -u)" --env "USERMAP_GID=$(id -g)"  \
  --volume $(pwd)/config/:/home/salt/data/config/ \
    cdalvaro/docker-salt-master:3001.1

SALT_API_TOKEN=$(curl -sSk https://localhost:8000/login \
  -H 'Accept: application/x-yaml' \
  -d username=salt_api \
  -d password=4wesome-Pass0rd \
  -d eauth=pam | grep 'token:' | cut -d' ' -f 4)

echo $SALT_API_TOKEN
4a5db8221475faa32522233640b4749651d70235

curl -sSk https://localhost:8000 \
  -H 'Accept: application/x-yaml' \
  -H 'X-Auth-Token: 4a5db8221475faa32522233640b4749651d70235' \
  -d client=runner \
  -d tgt='*' \
  -d fun=test.stream
return:
- true
```

I wil try again with Ubuntu 20.04

**Comment by vskubriev** [comment]
> I wil try again with Ubuntu 20.04

How quickly you wrote the tests. Well done.

I tried curl from macos (10.15.7)

```
curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

as a client and there is the same error:

```
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
```

Maybe I could be wrong with server configuration. Or may be it is something with ssl on master.

I will look for

**Comment by cdalvaro** [comment]
I have done the same check on *openSUSE Tumbleweed* and I get same results as on https://github.com/cdalvaro/docker-salt-master/issues/38#issuecomment-702793822

In this case, curl version is:

```
curl 7.69.1 (x86_64-suse-linux-gnu) libcurl/7.69.1 OpenSSL/1.1.1f-fips zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0
Release-Date: 2020-03-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

**Comment by cdalvaro** [comment]
I have done the same check on *openSUSE Tumbleweed* and I get same results as on https://github.com/cdalvaro/docker-salt-master/issues/38#issuecomment-702793822

In this case, curl version is:

```
curl 7.69.1 (x86_64-suse-linux-gnu) libcurl/7.69.1 OpenSSL/1.1.1f-fips zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0
Release-Date: 2020-03-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

**Comment by vskubriev** [comment]
So OpenSSL/1.1.1f the same as on ubuntu 20.04. Most likely this is my joint.

**Comment by cdalvaro** [comment]
> So OpenSSL/1.1.1f the same as on ubuntu 20.04. Most likely this is my problem.

Anyway, I really appreciate your help @vskubriev, this issue has helped me adding more tests!

Just for the record, I have tested this issue on *Ubuntu 20.04* too, and again the same result as on https://github.com/cdalvaro/docker-salt-master/issues/38#issuecomment-702793822

```
curl --version
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```
